/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/W7lgR1kJPTO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Booking() {
  return (
    <Card>
      <CardHeader className="pb-0">
        <CardTitle>Make a reservation</CardTitle>
        <CardDescription>Fill in the fields below to book your table.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-1">
            <Label className="text-sm" htmlFor="date">
              Date
            </Label>
            <Input className="w-full text-sm" id="date" placeholder="Enter a date" type="date" />
          </div>
          <div className="grid gap-1">
            <Label className="text-sm" htmlFor="time">
              Time
            </Label>
            <Input className="w-full text-sm" id="time" placeholder="Enter a time" type="time" />
          </div>
        </div>
        <div>
          <Label className="text-sm" htmlFor="people">
            Number of people
          </Label>
          <Input id="people" max={10} min={1} type="number" />
        </div>
      </CardContent>
      <CardFooter className=" flex justify-center">
        <Button size="sm" className="w-2/3">Book Now</Button>
      </CardFooter>
    </Card>
  )
}
